name: CI/CD Workflow with Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app:${{ github.sha }} .

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker requests

    - name: Run container security scan and remediation
      run: |
        python container_remediation.py my-app:${{ github.sha }}

    - name: Push remediated image
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker tag my-app:${{ github.sha }}-patched ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
